name: torch312
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - accelerate=1.12.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - backports.zstd=1.3.0
  - blas=1.0
  - boto3=1.42.19
  - botocore=1.42.19
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - cpuonly=2.0
  - datasets=4.4.1
  - dill=0.4.0
  - dnspython=2.8.0
  - email-validator=2.3.0
  - expat=2.7.3
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - filelock=3.20.3
  - freetype=2.14.1
  - frozenlist=1.8.0
  - fsspec=2025.10.0
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.1.8
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - hyperframe=6.1.0
  - idna=3.11
  - intel-openmp=2025.3.0
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libparquet=22.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsentencepiece=0.2.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.11.3
  - libuv=1.51.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.7.0
  - multiprocess=0.70.18
  - networkx=3.6.1
  - numexpr=2.11.0
  - numpy=2.4.1
  - openjpeg=2.5.3
  - openssl=3.6.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - peft=0.18.1
  - pillow=10.4.0
  - pip=25.3
  - propcache=0.4.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-multipart=0.0.20
  - python-tzdata=2025.3
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2025.11.05
  - regex=2025.11.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - s3transfer=0.16.0
  - sacremoses=0.1.1
  - safetensors=0.6.2
  - sentencepiece=0.2.1
  - sentencepiece-python=0.2.1
  - sentencepiece-spm=0.2.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.1
  - starlette=0.47.3
  - tbb=2021.13.0
  - tk=8.6.15
  - tokenizers=0.22.2
  - torchvision=0.20.1
  - tqdm=4.67.1
  - transformers=4.57.6
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - urllib3=2.6.3
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winloop=0.3.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - bitsandbytes==0.49.1
      - sympy==1.13.1
prefix: D:\anaconda3\envs\torch312
